### PR TITLE
Overhaul to bootstrap 4 and add scenes system which allows in app animation and static scene editing

### PR DESCRIPTION
**Pull request by williamoverton**
This is a large change but in my opinion a very helpful one.

As discussed on IRC, this is a large redesign of the dmx-web app which provides backwards compatibility but also adds a whole new "Scene" system which includes better animation support, a basic slider mode and scene editing.

### CODE REVIEW

**Comment by williamoverton** [comment]
FYI, node-dmx import is hardcoded to a folder on my system as im waiting for my PR to node-dmx to be merged. Just needs changing back before merge

**Comment by Fensterbank** [comment]
Looks like you put a lot of work in it. Nice. 👏
Would have been way fewer work to just create a new modern web app based on React or something. 😅

I was shocked my the changes (127k lines added) and realized, that you added (copied) some libraries to this repository.
You should install and use packages from npm. This is already a node powered webapp with a `package.json`, so there is no reason to copy that much code from other open source projects into our codebase.
So all things you have in `/public/vendor` should be referenced and installed through npm and should not be part of the code itself.

**Comment by williamoverton** [comment]
Yeah that's fair I can change that

**Comment by williamoverton** [comment]
As for why I didn't go down the react route or anything it's because I just simply haven't used react before, and it was only supposed to be a small change haha!

**Comment by williamoverton** [comment]
Reverted my commit where I moved vendor files into the codebase. I agree this should be npm based in the future but for now CDNs will do.

**Comment by williamoverton** [comment]
Still at +6,483 haha

**Comment by Fensterbank** [comment]
To be honest, I'm not sure about this pull request.
Obviously, this pull request is still far from ready. Or were you planning to open 13 more pull requests after the merge? 😉

Currently all people watching this repository get an email for every push you do, so I think it would make sense to close the pull request and reopen it when your branch has a working, tested and completed state.

On the other hand we should be careful here.
I know the current web interface is very simple and lowtech, but the core functionality of node-dmx is the library and the API. I'm not sure if we - as the node-dmx team - can and want to support a huge modern web app you are building. Don't get me wrong: I really appreciate you putting so much work into a new web interface, but looking at this, it feels a bit out of scope of node-dmx.

In the past we splitted library and api / web ui into two seperate projects to make it possible for developers to use the library without the API and web ui overhead.
My preference would be to also separate our legacy Web UI from the API. This would allow developers like you to build great and modern web interfaces using the API as npm package.
In fact, I would even propose to entirely remove the UI part from this repository and stay with the API. Then we could recommend or link your web interface as the official (or recommended) web interface for the node-dmx api.

We can compare it to https://github.com/moment: They are building and maintaining a great JavaScript library for datetime handling, but they don't develop, update and maintain a fancy React based date time picker in their repositories since that would be out of scope and not their core business.

What do you think, @wiedi and @bluemaex?

**Comment by williamoverton** [comment]
Ah sorry I didn't realise you all got emails when I pushed!

I totally agree with splitting out the ui from the http api, I think that makes a lot of sense. I think having a web UI is still a very useful thing to have though. I have mostly come to the end of the changes I wanted to do and everything now is just small changes and testing.

I understand your point about momentjs but would compare this project more to https://github.com/OpenLightingProject . They have the core project and then projects that work with the code, like the arduino colour mixing stuff (still being updated and worked on). I think there are lots of benefits of this being part of the node-dmx project rather than just being buried away in 0 star repos in github, people looking for node-dmx might also be interested in a web ui or a http api etc, meaning the project is more likely to attract contributors and users etc.

Cheers
Will

**Pull request closed without merging**
